version: '3.9'
services:

  rmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
    volumes:
      - ".rmq-data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
